pick = sample(1:9, 1)
if ( pick == 1 )
   print("You are doing expirement 1: Modern Climate, North Perturbation")
if ( pick == 2 )
   print("You are doing expirement 2: Modern Climate, South Perturbation")
if ( pick == 3 )
   print("You are doing expirement 3: Modern Climate, Both Perturbation")
if ( pick == 4 )
   print("You are doing expirement 4: Cold Climate, North Perturbation")
if ( pick == 5 )
   print("You are doing expirement 5: Cold Climate, South Perturbation")
if ( pick == 6 )
   print("You are doing expirement 6: Cold Climate, Both Perturbation")
if ( pick == 7 )
   print("You are doing expirement 7: Warm Climate, North Perturbation")
if ( pick == 8 )
   print("You are doing expirement 8: Warm Climate, South Perturbation")
if ( pick == 9 )
   print("You are doing expirement 9: Warm Climate, Both Perturbation")

